# yaml-language-server: $schema=https://unpkg.com/@powersync/service-schema@latest/json-schema/powersync-config.json

# Documentation https://docs.powersync.com/self-hosting/installation/powersync-service-setup
# https://github.com/powersync-ja/self-host-demo/blob/main/config/powersync.yaml

# Only environment variables with names starting with `PS_` can be substituted.
#
# e.g. With the environment variable `export PS_MONGO_URI=mongodb://localhost:27017`
# and YAML code:
#  uri: !env PS_MONGO_URI
# The YAML will resolve to:
#  uri: mongodb://localhost:27017

# Migrations:
#   # Migrations run automatically by default.
#   # Setting this to true will skip automatic migrations.
#   # Migrations can be triggered externally by altering the container `command`.
#   disable_auto_migration: true

replication:
  connections:
    - type: postgresql

      database: !env PS_DATABASE
      hostname: !env PS_HOST
      password: !env PS_PASSWORD
      port: !env PS_POSTGRES_PORT
      username: !env PS_USER

      # Optional if not using individual parameters
      # uri: !env PS_POSTGRES_URI

      # SSL settings
      sslmode: disable # 'verify-full' (default) or 'verify-ca' or 'disable'
      # 'disable' is OK for local/private networks, not for public networks

      # Required for verify-ca, optional for verify-full
      # This should be the certificate(s) content in PEM format
      # cacert: !env PS_PG_CA_CERT

      # Include a certificate here for HTTPs
      # This should be the certificate content in PEM format
      # client_certificate: !env PS_PG_CLIENT_CERT
      # This should be the key content in PEM format
      # client_private_key: !env PS_PG_CLIENT_PRIVATE_KEY

# Connection settings for sync bucket storage
storage:
  type: postgresql
  uri: !env PS_POSTGRES_STORAGE_URI
  sslmode: disable # 'verify-full' (default) or 'verify-ca' or 'disable'

  # use these if authentication is required
  # username: myuser
  # password: mypassword

# The port which the PowerSync API server will listen on
port: !env PS_PORT # Internal port

sync_rules:
  path: /config/sync_rules.yaml

# Client (application end user) authentication settings
client_auth:
  # Enable this if using Supabase Auth
  # supabase: true

  jwks_uri: !env PS_JWKS_URL

  # Optional static collection of public keys for JWT verification
  # jwks:
  #   #   keys:
  #   #     - kty: 'RSA'
  #   #       n: !env PS_JWK_N
  #   #       e: !env PS_JWK_E
  #   #       alg: 'RS256'
  #   #       kid: !env PS_JWK_KID
  #   keys:
  #     - kty: "oct"
  #       k: "thisisonlyforthediagnosticsappandshouldnotbeusedinproduction"
  #       alg: "HS256"

  # JWKS audience
  # audience: [!env PS_SERVER_URL]

# Settings for telemetry reporting
# See https://docs.powersync.com/self-hosting/telemetry
telemetry:
  # Opt out of reporting anonymized usage metrics to PowerSync telemetry service
  disable_telemetry_sharing: true

# Verify sync rules with:
#
# curl -X POST http://localhost:8080/api/sync-rules/v1/validate \
# -H "Authorization: Bearer abcd1234" \
# -H "Content-Type: application/yaml" \
# --data-binary "./sync_rules.yaml"
api:
  tokens:
    - !env PS_API_TOKEN
